Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,8 +3,12 @@ on:
   workflow_dispatch:
     inputs:
       BRANCH:
-        description: Kernel branch
+        description: Kernel Branch
         default: 'master'
+        required: true
+      DEFCONFIG:
+        description: Defconfig
+        default: 'a22x_defconfig'
         required: true
         
 jobs:
@@ -30,17 +34,57 @@ jobs:
         sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget aria2 curl lz4 -y
         sudo aptitude install libssl-dev -y
         
-    - name: Build Kernel
+    - name: Fetching Toolchains
       run: |
         if [ ! -d "clang" ]; then
-          curl -LSs https://raw.githubusercontent.com/rufnx/personal_patch/master/clang.sh | bash 12 clang
+          curl -LSs https://raw.githubusercontent.com/rufnx/personal_patch/master/clang.sh | bash -s 12 clang
         else
           echo "clang found, skip fetching clang"
         fi
 
         if [ ! -d "gcc" ]; then
-          curl -LSs https://raw.githubusercontent.com/rufnx/toolchains/README/clone.sh | bash androidcc-4.9 gcc
+          curl -LSs https://raw.githubusercontent.com/rufnx/toolchains/README/clone.sh | bash -s androidcc-4.9 gcc
         else
           echo "gcc found, skip fetching gcc"
         fi
       working-directory: kernel_root
+  
+    - name: Build Kernel
+      working-directory: kernel_root
+      run: |
+        export PATH=$(pwd)/clang/bin:$(pwd)/gcc/bin:$PATH
+        export USE_CCACHE=1
+        export KCFLAGS=-w
+        export KBUILD_BUILD_HOST=rufnxprjkt
+        export KBUILD_BUILD_USER=naifi
+        export DEFCONFIG=${{ inputs.DEFCONFIG }}
+
+        make ARCH=arm64 O=out $DEFCONFIG
+        sleep 2
+        
+        make -j$(nproc --all) \
+        O=out \
+        ARCH=arm64 \
+        LLVM=1 \
+        LLVM_IAS=1 \
+        CROSS_COMPILE=aarch64-linux-android- \
+        CLANG_TRIPLE=aarch64-linux-gnu- \
+        CONFIG_SECTION_MISMATCH_WARN_ONLY=y
+
+        if [ ! -f "out/arch/arm64/boot/Image.gz" ]; then
+          echo "build failed, exiting..."
+          exit 1
+        else
+          cd kernel_root
+          echo "build succes, continue to zip in AnyKernel3"
+          curl -LSs https://raw.githubusercontent.com/rufnx/personal_patch/master/ak3.sh | bash -s a22x ak3
+          cp out/arch/arm64/boot/Image.gz ak3/
+        fi
+
+        echo "completed all scripts..."
+    
+    - name: upload ouput
+      uses: actions/upload-artifact@v4
+      with:
+        name: AnyKernel3-${{ inputs.BRANCH }}-A226B
+        path: kernel_root/ak3/*
